[rig.test]
int = 10
float = 15
string = "option2"
bool = "false"
fixed_list = ""
list = ""
single_file = "No file chosen"
single_folder = "No file chosen"
multi_file = [ "/home/trygve/PhD/DarSIA_data/B049_images/DSC12935.JPG", "/home/trygve/PhD/DarSIA_data/B049_images/DSC12485.JPG",]

