"""Utilities to export/import reusable calibration bundles."""

from __future__ import annotations

import json
import logging
import shutil
from datetime import UTC, datetime
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

from darsia.presets.workflows.config.fluidflower_config import FluidFlowerConfig

logger = logging.getLogger(__name__)


def _zip_add_file(zip_file: ZipFile, file_path: Path, archive_path: Path) -> None:
    zip_file.write(file_path, arcname=str(archive_path))


def _zip_add_directory(
    zip_file: ZipFile, directory: Path, archive_root: Path
) -> list[Path]:
    written: list[Path] = []
    for file_path in sorted(directory.rglob("*")):
        if file_path.is_file():
            archive_path = archive_root / file_path.relative_to(directory)
            _zip_add_file(zip_file, file_path, archive_path)
            written.append(archive_path)
    return written


def _build_calibration_manifest(artifacts: dict[str, str]) -> dict[str, object]:
    return {
        "format_version": 1,
        "created_at_utc": datetime.now(UTC).isoformat(),
        "artifacts": artifacts,
    }


def _write_config_snippet(
    target_folder: Path,
    color_paths_folder: Path | None,
    color_to_mass_folder: Path | None,
    baseline_color_spectrum_folder: Path | None,
    color_range_file: Path | None,
) -> Path:
    lines = [
        "# Reusable calibration snippet generated by DarSIA",
        "# Copy the relevant entries into your analysis config file.",
        "",
    ]
    if color_paths_folder is not None:
        lines.extend(
            [
                "[color_paths]",
                f'calibration_file = "{color_paths_folder}"',
            ]
        )
        if baseline_color_spectrum_folder is not None:
            lines.append(
                f'baseline_color_spectrum_folder = "{baseline_color_spectrum_folder}"'
            )
        if color_range_file is not None:
            lines.append(f'color_range_file = "{color_range_file}"')
        lines.append("")
    if color_to_mass_folder is not None:
        lines.extend(
            [
                "[color_to_mass]",
                f'calibration_folder = "{color_to_mass_folder}"',
                "",
            ]
        )
    snippet_path = target_folder / "CONFIG_SNIPPET.toml"
    snippet_path.write_text("\n".join(lines))
    return snippet_path


def export_calibration_bundle(
    path: Path | list[Path], bundle: Path | None = None
) -> Path:
    """Export workflow calibration artifacts to a zipped bundle."""
    config = FluidFlowerConfig(path, require_data=False, require_results=False)

    if config.data is None:
        raise ValueError(
            "Missing [data] section; cannot determine default bundle location."
        )

    if bundle is None:
        bundle_dir = config.data.results / "calibration" / "bundles"
        bundle_dir.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
        bundle = bundle_dir / f"calibration_bundle_{timestamp}.zip"
    else:
        bundle = Path(bundle)
        bundle.parent.mkdir(parents=True, exist_ok=True)

    artifact_paths: dict[str, Path] = {}
    if config.color_paths is not None:
        if config.color_paths.calibration_file.exists():
            artifact_paths["color_paths"] = config.color_paths.calibration_file
        baseline_color_spectrum_folder = (
            config.color_paths.baseline_color_spectrum_folder
        )
        if baseline_color_spectrum_folder.exists():
            artifact_paths["baseline_color_spectrum"] = baseline_color_spectrum_folder
        color_range_file = config.color_paths.color_range_file.with_suffix(".json")
        if color_range_file.exists():
            artifact_paths["color_range"] = color_range_file
    if (
        config.color_to_mass is not None
        and config.color_to_mass.calibration_folder.exists()
    ):
        artifact_paths["color_to_mass"] = config.color_to_mass.calibration_folder

    if not artifact_paths:
        raise FileNotFoundError(
            "No calibration artifacts found to export. Run calibration first."
        )

    archive_root = Path("calibration_bundle")
    manifest_artifacts: dict[str, str] = {}
    with ZipFile(bundle, mode="w", compression=ZIP_DEFLATED) as zip_file:
        for key, src_path in artifact_paths.items():
            if src_path.is_dir():
                archive_path = archive_root / key
                _zip_add_directory(zip_file, src_path, archive_path)
            else:
                archive_path = archive_root / key / src_path.name
                _zip_add_file(zip_file, src_path, archive_path)
            manifest_artifacts[key] = str(archive_path)

        manifest = _build_calibration_manifest(manifest_artifacts)
        zip_file.writestr(
            str(archive_root / "manifest.json"),
            json.dumps(manifest, indent=2),
        )

    logger.info("Exported calibration bundle to %s", bundle)
    return bundle


def import_calibration_bundle(
    path: Path | list[Path],
    bundle: Path,
    target_folder: Path | None = None,
    overwrite: bool = False,
) -> dict[str, Path]:
    """Import a calibration bundle and provide config-ready path mapping."""
    config = FluidFlowerConfig(path, require_data=False, require_results=False)
    bundle = Path(bundle)
    if not bundle.exists():
        raise FileNotFoundError(f"Calibration bundle not found: {bundle}")

    if target_folder is None:
        if config.data is None:
            raise ValueError(
                "Missing [data] section; provide --calibration-target explicitly."
            )
        target_folder = config.data.results / "calibration" / "imported" / bundle.stem
    else:
        target_folder = Path(target_folder)

    if target_folder.exists():
        if not overwrite:
            raise FileExistsError(
                f"Target folder already exists: {target_folder}. "
                "Use overwrite=True or provide a new target folder."
            )
        shutil.rmtree(target_folder)
    target_folder.mkdir(parents=True, exist_ok=True)

    with ZipFile(bundle, mode="r") as zip_file:
        for member in zip_file.infolist():
            destination = target_folder / member.filename
            if not destination.resolve().is_relative_to(target_folder.resolve()):
                raise ValueError(f"Unsafe archive member path: {member.filename}")
        zip_file.extractall(target_folder)

    root = target_folder / "calibration_bundle"
    if not root.exists():
        root = target_folder

    paths = {
        "color_paths": root / "color_paths",
        "color_to_mass": root / "color_to_mass",
        "baseline_color_spectrum": root / "baseline_color_spectrum",
        "color_range": root / "color_range" / "color_range.json",
    }
    result = {k: v for k, v in paths.items() if v.exists()}

    snippet_path = _write_config_snippet(
        target_folder=target_folder,
        color_paths_folder=result.get("color_paths"),
        color_to_mass_folder=result.get("color_to_mass"),
        baseline_color_spectrum_folder=result.get("baseline_color_spectrum"),
        color_range_file=result.get("color_range"),
    )
    logger.info("Imported calibration bundle to %s", target_folder)
    logger.info("Config snippet written to %s", snippet_path)
    return result
