"""Utilities to export/import reusable calibration bundles."""

from __future__ import annotations

import json
import logging
import shutil
from datetime import UTC, datetime
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

from darsia.presets.workflows.config.fluidflower_config import FluidFlowerConfig

logger = logging.getLogger(__name__)


def _zip_add_file(zip_file: ZipFile, file_path: Path, archive_path: Path) -> None:
    zip_file.write(file_path, arcname=str(archive_path))


def _zip_add_directory(
    zip_file: ZipFile, directory: Path, archive_root: Path
) -> list[Path]:
    written: list[Path] = []
    for file_path in sorted(directory.rglob("*")):
        if file_path.is_file():
            archive_path = archive_root / file_path.relative_to(directory)
            _zip_add_file(zip_file, file_path, archive_path)
            written.append(archive_path)
    return written


def _build_calibration_manifest(artifacts: dict[str, str]) -> dict[str, object]:
    return {
        "format_version": 1,
        "created_at_utc": datetime.now(UTC).isoformat(),
        "artifacts": artifacts,
    }


def _write_config_snippet(
    target_folder: Path,
    color_paths_folder: Path | None,
    color_to_mass_folder: Path | None,
    baseline_color_spectrum_folder: Path | None,
    color_range_file: Path | None,
) -> Path:
    lines = [
        "# Reusable calibration snippet generated by DarSIA",
        "# Copy the relevant entries into your analysis config file.",
        "",
    ]
    if color_paths_folder is not None:
        lines.extend(
            [
                "[color_paths]",
                f'calibration_file = "{color_paths_folder}"',
            ]
        )
        if baseline_color_spectrum_folder is not None:
            lines.append(
                f'baseline_color_spectrum_folder = "{baseline_color_spectrum_folder}"'
            )
        if color_range_file is not None:
            lines.append(f'color_range_file = "{color_range_file}"')
        lines.append("")
    if color_to_mass_folder is not None:
        lines.extend(
            [
                "[color_to_mass]",
                f'calibration_folder = "{color_to_mass_folder}"',
                "",
            ]
        )
    snippet_path = target_folder / "CONFIG_SNIPPET.toml"
    snippet_path.write_text("\n".join(lines))
    return snippet_path


def export_calibration_bundle(
    path: Path | list[Path], bundle: Path | None = None
) -> Path:
    """Export workflow calibration artifacts to a zipped bundle."""
    config = FluidFlowerConfig(path, require_data=False, require_results=False)

    if config.data is None:
        raise ValueError(
            "Missing [data] section; cannot determine default bundle location."
        )
    if config.data.results is None:
        raise ValueError(
            "Missing [data].results value; cannot determine default bundle location."
        )

    if bundle is None:
        bundle_dir = config.data.results / "calibration" / "bundles"
        bundle_dir.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
        bundle = bundle_dir / f"calibration_bundle_{timestamp}.zip"
    else:
        bundle = Path(bundle)
        bundle.parent.mkdir(parents=True, exist_ok=True)

    artifact_paths: dict[str, Path] = {}
    if config.color_paths is not None:
        if config.color_paths.calibration_file.exists():
            artifact_paths["color_paths"] = config.color_paths.calibration_file
        baseline_color_spectrum_folder = (
            config.color_paths.baseline_color_spectrum_folder
        )
        if baseline_color_spectrum_folder.exists():
            artifact_paths["baseline_color_spectrum"] = baseline_color_spectrum_folder
        color_range_file = config.color_paths.color_range_file.with_suffix(".json")
        if color_range_file.exists():
            artifact_paths["color_range"] = color_range_file
    if (
        config.color_to_mass is not None
        and config.color_to_mass.calibration_folder.exists()
    ):
        artifact_paths["color_to_mass"] = config.color_to_mass.calibration_folder

    if not artifact_paths:
        raise FileNotFoundError(
            "No calibration artifacts found to export. Run calibration first."
        )

    archive_root = Path("calibration_bundle")
    manifest_artifacts: dict[str, str] = {}
    with ZipFile(bundle, mode="w", compression=ZIP_DEFLATED) as zip_file:
        for key, src_path in artifact_paths.items():
            if src_path.is_dir():
                archive_path = archive_root / key
                _zip_add_directory(zip_file, src_path, archive_path)
            else:
                archive_path = archive_root / key / src_path.name
                _zip_add_file(zip_file, src_path, archive_path)
            manifest_artifacts[key] = str(archive_path)

        manifest = _build_calibration_manifest(manifest_artifacts)
        zip_file.writestr(
            str(archive_root / "manifest.json"),
            json.dumps(manifest, indent=2),
        )

    logger.info("Exported calibration bundle to %s", bundle)
    return bundle


def import_calibration_bundle(
    path: Path | list[Path],
    bundle: Path,
    target_folder: Path | None = None,
    overwrite: bool = False,
) -> dict[str, Path]:
    """Import a calibration bundle and provide config-ready path mapping."""
    config = FluidFlowerConfig(path, require_data=False, require_results=False)
    bundle = Path(bundle)
    if not bundle.exists():
        raise FileNotFoundError(f"Calibration bundle not found: {bundle}")

    if config.data is None or config.data.results is None:
        raise ValueError("Missing [data].results value in config.")

    calibration_root = config.data.results / "calibration"
    if target_folder is None:
        target_folder = calibration_root
    else:
        target_folder = Path(target_folder)
        if target_folder.exists():
            if not overwrite:
                raise FileExistsError(
                    f"Target folder already exists: {target_folder}. "
                    "Use overwrite=True or provide a new target folder."
                )
            shutil.rmtree(target_folder)

    target_folder.mkdir(parents=True, exist_ok=True)

    destination_roots: dict[str, Path] = {
        "color_paths": (
            config.color_paths.calibration_file
            if target_folder == calibration_root and config.color_paths is not None
            else target_folder / "color_paths"
        ),
        "color_to_mass": (
            config.color_to_mass.calibration_folder
            if target_folder == calibration_root and config.color_to_mass is not None
            else target_folder / "color_to_mass"
        ),
        "baseline_color_spectrum": (
            config.color_paths.baseline_color_spectrum_folder
            if target_folder == calibration_root and config.color_paths is not None
            else target_folder / "baseline_color_spectrum"
        ),
        "color_range": (
            config.color_paths.color_range_file.with_suffix(".json")
            if target_folder == calibration_root and config.color_paths is not None
            else target_folder / "color_range.json"
        ),
    }

    destination_root_paths = [
        destination_roots["color_paths"],
        destination_roots["color_to_mass"],
        destination_roots["baseline_color_spectrum"],
        destination_roots["color_range"],
    ]
    existing_destinations = [path for path in destination_root_paths if path.exists()]
    if existing_destinations and not overwrite:
        raise FileExistsError(
            f"Calibration destination already exists: {existing_destinations[0]}. "
            "Use overwrite=True or provide a new target folder."
        )
    if overwrite:
        for destination in existing_destinations:
            if destination.is_dir():
                shutil.rmtree(destination)
            else:
                destination.unlink()

    artifact_members: dict[str, list[tuple[object, Path]]] = {
        "color_paths": [],
        "color_to_mass": [],
        "baseline_color_spectrum": [],
        "color_range": [],
    }
    with ZipFile(bundle, mode="r") as zip_file:
        for member in zip_file.infolist():
            member_path = Path(member.filename)
            if member_path.is_absolute() or ".." in member_path.parts:
                raise ValueError(f"Unsafe archive member path: {member.filename}")
            if member_path.parts and member_path.parts[0] == "calibration_bundle":
                member_path = Path(*member_path.parts[1:])
            if len(member_path.parts) < 2:
                continue
            artifact = member_path.parts[0]
            if artifact not in artifact_members or member.is_dir():
                continue
            artifact_members[artifact].append((member, Path(*member_path.parts[1:])))

        for artifact, members in artifact_members.items():
            destination_root = destination_roots[artifact]
            # color_range is stored as a single file destination, while the others
            # are directories receiving extracted members.
            safe_base = (
                destination_root
                if destination_root.is_dir() or artifact != "color_range"
                else destination_root.parent
            )
            for member, relative_path in members:
                if artifact == "color_range":
                    destination = destination_root
                else:
                    destination = destination_root / relative_path
                if not destination.resolve().is_relative_to(safe_base.resolve()):
                    raise ValueError(f"Unsafe archive member path: {member.filename}")
                destination.parent.mkdir(parents=True, exist_ok=True)
                with zip_file.open(member) as src, destination.open("wb") as dst:
                    shutil.copyfileobj(src, dst)

    result = {
        key: value
        for key, value in destination_roots.items()
        if value.exists()
        and key in {"color_paths", "color_to_mass", "baseline_color_spectrum"}
    }
    if destination_roots["color_range"].exists():
        result["color_range"] = destination_roots["color_range"]

    snippet_path = _write_config_snippet(
        target_folder=target_folder,
        color_paths_folder=result.get("color_paths"),
        color_to_mass_folder=result.get("color_to_mass"),
        baseline_color_spectrum_folder=result.get("baseline_color_spectrum"),
        color_range_file=result.get("color_range"),
    )
    logger.info("Imported calibration bundle to %s", target_folder)
    logger.info("Config snippet written to %s", snippet_path)
    return result
