"""Utilities to export/import reusable calibration bundles."""

from __future__ import annotations

import json
import logging
import shutil
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Literal
from zipfile import ZIP_DEFLATED, ZipFile, is_zipfile

from darsia.presets.workflows.config.fluidflower_config import FluidFlowerConfig

logger = logging.getLogger(__name__)


def _calibration_color_root(config: FluidFlowerConfig) -> Path:
    if config.data is None or config.data.results is None:
        raise ValueError("Missing [data].results value in config.")
    return config.data.results / "calibration" / "color"


@dataclass(frozen=True)
class _BundleEntry:
    source: str | Path
    rel_path: Path
    source_kind: Literal["zip", "file"]


def _sanitize_rel_path(rel: Path, source_label: str) -> Path:
    if rel.is_absolute() or ".." in rel.parts:
        raise ValueError(f"Unsafe bundle entry path in {source_label}: {rel}")
    return rel


def _normalize_bundle_rel_paths(
    members: list[tuple[str, Path]],
    *,
    default_embedding: str | None,
    source_label: str,
) -> list[tuple[str, Path]]:
    safe_members: list[tuple[str, Path]] = []
    for name, rel in members:
        rel = _sanitize_rel_path(rel, source_label)
        if rel.parts:
            safe_members.append((name, rel))
    if not safe_members:
        raise ValueError(f"Calibration bundle contains no files: {source_label}")

    prefixes = [("calibration", "color"), ("calibration",), ("color",)]
    stripped_members: list[tuple[str, Path]] = []
    for prefix in prefixes:
        prefix_matches: list[tuple[str, Path]] = []
        for name, rel in safe_members:
            if rel.parts[: len(prefix)] == prefix:
                stripped = Path(*rel.parts[len(prefix) :])
                if stripped.parts:
                    prefix_matches.append((name, stripped))
        if prefix_matches:
            stripped_members = prefix_matches
            break
    if not stripped_members:
        stripped_members = list(safe_members)

    manifest = Path("manifest.json")
    payload = [(name, rel) for name, rel in stripped_members if rel != manifest]
    extra = [(name, rel) for name, rel in stripped_members if rel == manifest]
    if not payload:
        raise ValueError(
            f"Calibration bundle contains no calibration entries: {source_label}"
        )
    if any(len(rel.parts) >= 2 for _, rel in payload):
        payload = [(name, rel) for name, rel in payload if len(rel.parts) >= 2]
    else:
        if default_embedding:
            payload = [
                (name, Path(default_embedding) / rel) for name, rel in payload
            ]
        else:
            raise ValueError(
                "Calibration bundle must contain embedding folders (for example "
                "'calibration/color/<id>/...')."
            )
    return payload + extra


def _bundle_entries(bundle: Path) -> list[_BundleEntry]:
    if bundle.is_dir():
        members = [
            (str(path.relative_to(bundle)), path.relative_to(bundle))
            for path in bundle.rglob("*")
            if path.is_file()
        ]
        normalized = _normalize_bundle_rel_paths(
            members, default_embedding=bundle.name, source_label=str(bundle)
        )
        return [
            _BundleEntry(
                source=bundle / Path(name),
                rel_path=rel,
                source_kind="file",
            )
            for name, rel in normalized
        ]

    if not bundle.exists():
        raise FileNotFoundError(f"Calibration bundle not found: {bundle}")
    if not is_zipfile(bundle):
        raise ValueError(
            f"Calibration bundle must be a zip file or directory: {bundle}"
        )
    with ZipFile(bundle, mode="r") as zip_file:
        members = [
            (info.filename, Path(info.filename))
            for info in zip_file.infolist()
            if not info.is_dir()
        ]
    normalized = _normalize_bundle_rel_paths(
        members, default_embedding=bundle.stem, source_label=str(bundle)
    )
    return [
        _BundleEntry(source=name, rel_path=rel, source_kind="zip")
        for name, rel in normalized
    ]


def _collect_bundle_targets(
    bundle: Path, destination_root: Path
) -> list[tuple[_BundleEntry, Path]]:
    targets: list[tuple[_BundleEntry, Path]] = []
    for entry in _bundle_entries(bundle):
        dst = destination_root / entry.rel_path
        if not dst.resolve().is_relative_to(destination_root.resolve()):
            raise ValueError(f"Unsafe bundle entry path: {entry.rel_path}")
        targets.append((entry, dst))
    return targets


def _write_config_snippet(target_root: Path, embedding_ids: list[str]) -> Path:
    lines = [
        "# Reusable calibration snippet generated by DarSIA",
        "# Copy relevant entries into your workflow config.",
        "",
        "[analysis.mass]",
    ]
    if embedding_ids:
        lines.append(f'color = "{embedding_ids[0]}"')
    else:
        lines.append('color = "<embedding_id>"')
    lines.extend(
        [
            "",
            "[calibration.color]",
            'color = "<embedding_id>"',
            "",
            "[calibration.mass]",
            'color = "<embedding_id>"',
            "",
        ]
    )
    snippet_path = target_root / "CONFIG_SNIPPET.toml"
    snippet_path.write_text("\n".join(lines))
    return snippet_path


def preview_calibration_bundle_import_conflicts(
    path: Path | list[Path], bundle: Path, target_folder: Path | None = None
) -> list[Path]:
    """Preview destination files that would be overwritten during import."""
    config = FluidFlowerConfig(path, require_data=False, require_results=False)
    bundle = Path(bundle)

    target_root = (
        _calibration_color_root(config)
        if target_folder is None
        else Path(target_folder)
    )
    targets = _collect_bundle_targets(bundle, target_root)
    return sorted({dst for _, dst in targets if dst.exists()})


def export_calibration_bundle(
    path: Path | list[Path], bundle: Path | None = None
) -> Path:
    """Export workflow calibration artifacts to a zipped bundle."""
    config = FluidFlowerConfig(path, require_data=False, require_results=False)
    calibration_root = _calibration_color_root(config)
    if not calibration_root.exists():
        raise FileNotFoundError(
            f"No calibration/color folder found to export: {calibration_root}"
        )

    embedding_folders = sorted([p for p in calibration_root.iterdir() if p.is_dir()])
    if len(embedding_folders) == 0:
        raise FileNotFoundError(
            "No color embedding calibration folders found to export."
        )

    assert config.data is not None
    assert config.data.results is not None
    results_root = config.data.results

    if bundle is None:
        bundle_dir = results_root / "calibration"
        bundle_dir.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
        bundle = bundle_dir / f"calibration_{timestamp}.zip"
    else:
        bundle = Path(bundle)
        bundle.parent.mkdir(parents=True, exist_ok=True)

    archive_root = Path("calibration") / "color"
    with ZipFile(bundle, mode="w", compression=ZIP_DEFLATED) as zip_file:
        for embedding_folder in embedding_folders:
            for file_path in sorted(embedding_folder.rglob("*")):
                if file_path.is_file():
                    archive_path = (
                        archive_root
                        / embedding_folder.name
                        / file_path.relative_to(embedding_folder)
                    )
                    zip_file.write(file_path, arcname=str(archive_path))
        zip_file.writestr(
            str(archive_root / "manifest.json"),
            json.dumps(
                {
                    "format_version": 2,
                    "created_at_utc": datetime.now(UTC).isoformat(),
                    "embeddings": [p.name for p in embedding_folders],
                },
                indent=2,
            ),
        )

    logger.info("Exported calibration bundle to %s", bundle)
    return bundle


def import_calibration_bundle(
    path: Path | list[Path],
    bundle: Path,
    target_folder: Path | None = None,
    overwrite: bool = False,
    conflict_action: Literal["error", "overwrite_all", "skip_all"] | None = None,
) -> dict[str, Path]:
    """Import a calibration bundle (zip or folder) and provide config-ready paths."""
    config = FluidFlowerConfig(path, require_data=False, require_results=False)
    bundle = Path(bundle)

    destination_root = (
        _calibration_color_root(config)
        if target_folder is None
        else Path(target_folder)
    )
    destination_root.mkdir(parents=True, exist_ok=True)

    if conflict_action is not None and conflict_action not in {
        "error",
        "overwrite_all",
        "skip_all",
    }:
        raise ValueError(f"Unsupported conflict action: {conflict_action}")
    action = conflict_action or ("overwrite_all" if overwrite else "error")

    targets = _collect_bundle_targets(bundle, destination_root)
    conflicts = [dst for _, dst in targets if dst.exists()]
    if conflicts and action == "error":
        raise FileExistsError(
            f"Calibration import would overwrite existing file: {conflicts[0]}. "
            "Use overwrite=True/conflict_action='overwrite_all' or "
            "conflict_action='skip_all'."
        )

    if bundle.is_dir():
        for entry, dst in targets:
            if dst.exists() and action == "skip_all":
                continue
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(Path(entry.source), dst)
    else:
        with ZipFile(bundle, mode="r") as zip_file:
            for entry, dst in targets:
                if dst.exists() and action == "skip_all":
                    continue
                dst.parent.mkdir(parents=True, exist_ok=True)
                with zip_file.open(str(entry.source)) as src, dst.open("wb") as out:
                    shutil.copyfileobj(src, out)

    embedding_ids = sorted([p.name for p in destination_root.iterdir() if p.is_dir()])
    snippet_path = _write_config_snippet(destination_root, embedding_ids)
    logger.info("Imported calibration bundle to %s", destination_root)
    logger.info("Config snippet written to %s", snippet_path)
    return {
        embedding_id: destination_root / embedding_id for embedding_id in embedding_ids
    }
